# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1100, 350)
        Form.setMinimumSize(QtCore.QSize(1100, 350))
        Form.setMaximumSize(QtCore.QSize(1100, 350))
        Form.setSizeIncrement(QtCore.QSize(700, 650))
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(0, 0, 1100, 700))
        self.widget.setMinimumSize(QtCore.QSize(1100, 700))
        self.widget.setMaximumSize(QtCore.QSize(1100, 700))
        self.widget.setStyleSheet("QWidget#widget {\n"
"background-color: #EBEBEB;\n"
"}\n"
"")
        self.widget.setObjectName("widget")
        self.pushButton_stop = QtWidgets.QPushButton(self.widget)
        self.pushButton_stop.setGeometry(QtCore.QRect(530, 260, 70, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_stop.setFont(font)
        self.pushButton_stop.setStyleSheet("QPushButton{\n"
"background-color: #FFA500;\n"
"color:rgb(0, 0, 0)\n"
"}\n"
"QPushButton{border-radius:6px;}\n"
"QPushButton:pressed{\n"
"border:2px solid rgb(126, 188, 89, 0);}")
        self.pushButton_stop.setObjectName("pushButton_stop")
        self.pushButton_apply = QtWidgets.QPushButton(self.widget)
        self.pushButton_apply.setGeometry(QtCore.QRect(640, 260, 70, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_apply.setFont(font)
        self.pushButton_apply.setStyleSheet("QPushButton{\n"
"background-color: #A2A2A2;\n"
"color:rgb(0, 0, 0)\n"
"}\n"
"QPushButton{border-radius:6px;}\n"
"QPushButton:pressed{\n"
"border:2px solid rgb(126, 188, 89, 0);}")
        self.pushButton_apply.setObjectName("pushButton_apply")
        self.pushButton_start = QtWidgets.QPushButton(self.widget)
        self.pushButton_start.setGeometry(QtCore.QRect(420, 260, 70, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_start.setFont(font)
        self.pushButton_start.setStyleSheet("QPushButton{\n"
"background-color: #FFA500;\n"
"color:rgb(0, 0, 0)\n"
"}\n"
"QPushButton{border-radius:6px;}\n"
"QPushButton:pressed{\n"
"border:2px solid rgb(126, 188, 89, 0);}")
        self.pushButton_start.setObjectName("pushButton_start")
        self.layoutWidget = QtWidgets.QWidget(self.widget)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 30, 351, 182))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.splitter_4 = QtWidgets.QSplitter(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter_4.sizePolicy().hasHeightForWidth())
        self.splitter_4.setSizePolicy(sizePolicy)
        self.splitter_4.setMaximumSize(QtCore.QSize(344, 16777215))
        self.splitter_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.splitter_4.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_4.setObjectName("splitter_4")
        self.label_init_x_offset = QtWidgets.QLabel(self.splitter_4)
        self.label_init_x_offset.setMinimumSize(QtCore.QSize(280, 0))
        self.label_init_x_offset.setMaximumSize(QtCore.QSize(280, 16777215))
        self.label_init_x_offset.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_init_x_offset.setObjectName("label_init_x_offset")
        self.lineEdit_init_x_offset = QtWidgets.QLineEdit(self.splitter_4)
        self.lineEdit_init_x_offset.setMinimumSize(QtCore.QSize(60, 0))
        self.lineEdit_init_x_offset.setMaximumSize(QtCore.QSize(60, 16777215))
        self.lineEdit_init_x_offset.setObjectName("lineEdit_init_x_offset")
        self.verticalLayout.addWidget(self.splitter_4)
        self.splitter_5 = QtWidgets.QSplitter(self.layoutWidget)
        self.splitter_5.setMaximumSize(QtCore.QSize(344, 16777215))
        self.splitter_5.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_5.setObjectName("splitter_5")
        self.label_2 = QtWidgets.QLabel(self.splitter_5)
        self.label_2.setMinimumSize(QtCore.QSize(280, 0))
        self.label_2.setMaximumSize(QtCore.QSize(280, 16777215))
        self.label_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.lineEdit_init_y_offset = QtWidgets.QLineEdit(self.splitter_5)
        self.lineEdit_init_y_offset.setMinimumSize(QtCore.QSize(60, 0))
        self.lineEdit_init_y_offset.setMaximumSize(QtCore.QSize(60, 16777215))
        self.lineEdit_init_y_offset.setObjectName("lineEdit_init_y_offset")
        self.verticalLayout.addWidget(self.splitter_5)
        self.splitter_22 = QtWidgets.QSplitter(self.layoutWidget)
        self.splitter_22.setMaximumSize(QtCore.QSize(344, 16777215))
        self.splitter_22.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_22.setObjectName("splitter_22")
        self.label_init_z_offset = QtWidgets.QLabel(self.splitter_22)
        self.label_init_z_offset.setMinimumSize(QtCore.QSize(280, 0))
        self.label_init_z_offset.setMaximumSize(QtCore.QSize(280, 16777215))
        self.label_init_z_offset.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_init_z_offset.setObjectName("label_init_z_offset")
        self.lineEdit_init_z_offset = QtWidgets.QLineEdit(self.splitter_22)
        self.lineEdit_init_z_offset.setMinimumSize(QtCore.QSize(60, 0))
        self.lineEdit_init_z_offset.setMaximumSize(QtCore.QSize(60, 16777215))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lineEdit_init_z_offset.setFont(font)
        self.lineEdit_init_z_offset.setObjectName("lineEdit_init_z_offset")
        self.verticalLayout.addWidget(self.splitter_22)
        self.splitter_6 = QtWidgets.QSplitter(self.layoutWidget)
        self.splitter_6.setMaximumSize(QtCore.QSize(344, 16777215))
        self.splitter_6.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_6.setObjectName("splitter_6")
        self.label_init_roll_offset = QtWidgets.QLabel(self.splitter_6)
        self.label_init_roll_offset.setMinimumSize(QtCore.QSize(280, 0))
        self.label_init_roll_offset.setMaximumSize(QtCore.QSize(280, 16777215))
        self.label_init_roll_offset.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_init_roll_offset.setObjectName("label_init_roll_offset")
        self.lineEdit_init_roll_offset = QtWidgets.QLineEdit(self.splitter_6)
        self.lineEdit_init_roll_offset.setMinimumSize(QtCore.QSize(60, 0))
        self.lineEdit_init_roll_offset.setMaximumSize(QtCore.QSize(60, 16777215))
        self.lineEdit_init_roll_offset.setObjectName("lineEdit_init_roll_offset")
        self.verticalLayout.addWidget(self.splitter_6)
        self.splitter_7 = QtWidgets.QSplitter(self.layoutWidget)
        self.splitter_7.setMaximumSize(QtCore.QSize(344, 16777215))
        self.splitter_7.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_7.setObjectName("splitter_7")
        self.label_init_pitch_offset = QtWidgets.QLabel(self.splitter_7)
        self.label_init_pitch_offset.setMinimumSize(QtCore.QSize(280, 0))
        self.label_init_pitch_offset.setMaximumSize(QtCore.QSize(280, 16777215))
        self.label_init_pitch_offset.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_init_pitch_offset.setObjectName("label_init_pitch_offset")
        self.lineEdit_init_pitch_offset = QtWidgets.QLineEdit(self.splitter_7)
        self.lineEdit_init_pitch_offset.setMinimumSize(QtCore.QSize(60, 0))
        self.lineEdit_init_pitch_offset.setMaximumSize(QtCore.QSize(60, 16777215))
        self.lineEdit_init_pitch_offset.setObjectName("lineEdit_init_pitch_offset")
        self.verticalLayout.addWidget(self.splitter_7)
        self.splitter_8 = QtWidgets.QSplitter(self.layoutWidget)
        self.splitter_8.setMaximumSize(QtCore.QSize(344, 16777215))
        self.splitter_8.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_8.setObjectName("splitter_8")
        self.label_init_yaw_offset = QtWidgets.QLabel(self.splitter_8)
        self.label_init_yaw_offset.setMinimumSize(QtCore.QSize(280, 0))
        self.label_init_yaw_offset.setMaximumSize(QtCore.QSize(280, 16777215))
        self.label_init_yaw_offset.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_init_yaw_offset.setObjectName("label_init_yaw_offset")
        self.lineEdit_init_yaw_offset = QtWidgets.QLineEdit(self.splitter_8)
        self.lineEdit_init_yaw_offset.setMinimumSize(QtCore.QSize(60, 0))
        self.lineEdit_init_yaw_offset.setMaximumSize(QtCore.QSize(60, 16777215))
        self.lineEdit_init_yaw_offset.setObjectName("lineEdit_init_yaw_offset")
        self.verticalLayout.addWidget(self.splitter_8)
        self.layoutWidget1 = QtWidgets.QWidget(self.widget)
        self.layoutWidget1.setGeometry(QtCore.QRect(390, 30, 351, 182))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.splitter_9 = QtWidgets.QSplitter(self.layoutWidget1)
        self.splitter_9.setMaximumSize(QtCore.QSize(344, 16777215))
        self.splitter_9.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_9.setObjectName("splitter_9")
        self.label_period_time = QtWidgets.QLabel(self.splitter_9)
        self.label_period_time.setMinimumSize(QtCore.QSize(280, 0))
        self.label_period_time.setMaximumSize(QtCore.QSize(280, 16777215))
        self.label_period_time.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_period_time.setObjectName("label_period_time")
        self.lineEdit_period_time = QtWidgets.QLineEdit(self.splitter_9)
        self.lineEdit_period_time.setMinimumSize(QtCore.QSize(60, 0))
        self.lineEdit_period_time.setMaximumSize(QtCore.QSize(60, 16777215))
        self.lineEdit_period_time.setObjectName("lineEdit_period_time")
        self.verticalLayout_2.addWidget(self.splitter_9)
        self.splitter_10 = QtWidgets.QSplitter(self.layoutWidget1)
        self.splitter_10.setMaximumSize(QtCore.QSize(344, 16777215))
        self.splitter_10.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_10.setObjectName("splitter_10")
        self.label_dsp_ratio = QtWidgets.QLabel(self.splitter_10)
        self.label_dsp_ratio.setMinimumSize(QtCore.QSize(280, 0))
        self.label_dsp_ratio.setMaximumSize(QtCore.QSize(280, 16777215))
        self.label_dsp_ratio.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_dsp_ratio.setObjectName("label_dsp_ratio")
        self.lineEdit_dsp_ratio = QtWidgets.QLineEdit(self.splitter_10)
        self.lineEdit_dsp_ratio.setMinimumSize(QtCore.QSize(60, 0))
        self.lineEdit_dsp_ratio.setMaximumSize(QtCore.QSize(60, 16777215))
        self.lineEdit_dsp_ratio.setObjectName("lineEdit_dsp_ratio")
        self.verticalLayout_2.addWidget(self.splitter_10)
        self.splitter_11 = QtWidgets.QSplitter(self.layoutWidget1)
        self.splitter_11.setMaximumSize(QtCore.QSize(344, 16777215))
        self.splitter_11.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_11.setObjectName("splitter_11")
        self.label_step_fb_ratio = QtWidgets.QLabel(self.splitter_11)
        self.label_step_fb_ratio.setMinimumSize(QtCore.QSize(280, 0))
        self.label_step_fb_ratio.setMaximumSize(QtCore.QSize(280, 16777215))
        self.label_step_fb_ratio.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_step_fb_ratio.setObjectName("label_step_fb_ratio")
        self.lineEdit_step_fb_ratio = QtWidgets.QLineEdit(self.splitter_11)
        self.lineEdit_step_fb_ratio.setMinimumSize(QtCore.QSize(60, 0))
        self.lineEdit_step_fb_ratio.setMaximumSize(QtCore.QSize(60, 16777215))
        self.lineEdit_step_fb_ratio.setObjectName("lineEdit_step_fb_ratio")
        self.verticalLayout_2.addWidget(self.splitter_11)
        self.splitter_17 = QtWidgets.QSplitter(self.layoutWidget1)
        self.splitter_17.setMaximumSize(QtCore.QSize(344, 16777215))
        self.splitter_17.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_17.setObjectName("splitter_17")
        self.label_y_swap_amplitude = QtWidgets.QLabel(self.splitter_17)
        self.label_y_swap_amplitude.setMinimumSize(QtCore.QSize(280, 0))
        self.label_y_swap_amplitude.setMaximumSize(QtCore.QSize(280, 16777215))
        self.label_y_swap_amplitude.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_y_swap_amplitude.setObjectName("label_y_swap_amplitude")
        self.lineEdit_y_swap_amplitude = QtWidgets.QLineEdit(self.splitter_17)
        self.lineEdit_y_swap_amplitude.setMinimumSize(QtCore.QSize(60, 0))
        self.lineEdit_y_swap_amplitude.setMaximumSize(QtCore.QSize(60, 16777215))
        self.lineEdit_y_swap_amplitude.setObjectName("lineEdit_y_swap_amplitude")
        self.verticalLayout_2.addWidget(self.splitter_17)
        self.splitter_18 = QtWidgets.QSplitter(self.layoutWidget1)
        self.splitter_18.setMaximumSize(QtCore.QSize(344, 16777215))
        self.splitter_18.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_18.setObjectName("splitter_18")
        self.label_z_swap_amplitude = QtWidgets.QLabel(self.splitter_18)
        self.label_z_swap_amplitude.setMinimumSize(QtCore.QSize(280, 0))
        self.label_z_swap_amplitude.setMaximumSize(QtCore.QSize(280, 16777215))
        self.label_z_swap_amplitude.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_z_swap_amplitude.setObjectName("label_z_swap_amplitude")
        self.lineEdit_z_swap_amplitude = QtWidgets.QLineEdit(self.splitter_18)
        self.lineEdit_z_swap_amplitude.setMinimumSize(QtCore.QSize(60, 0))
        self.lineEdit_z_swap_amplitude.setMaximumSize(QtCore.QSize(60, 16777215))
        self.lineEdit_z_swap_amplitude.setObjectName("lineEdit_z_swap_amplitude")
        self.verticalLayout_2.addWidget(self.splitter_18)
        self.splitter_19 = QtWidgets.QSplitter(self.layoutWidget1)
        self.splitter_19.setMaximumSize(QtCore.QSize(344, 16777215))
        self.splitter_19.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_19.setObjectName("splitter_19")
        self.label_pelvis_offset = QtWidgets.QLabel(self.splitter_19)
        self.label_pelvis_offset.setMinimumSize(QtCore.QSize(280, 0))
        self.label_pelvis_offset.setMaximumSize(QtCore.QSize(280, 16777215))
        self.label_pelvis_offset.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_pelvis_offset.setObjectName("label_pelvis_offset")
        self.lineEdit_pelvis_offset = QtWidgets.QLineEdit(self.splitter_19)
        self.lineEdit_pelvis_offset.setMinimumSize(QtCore.QSize(60, 0))
        self.lineEdit_pelvis_offset.setMaximumSize(QtCore.QSize(60, 16777215))
        self.lineEdit_pelvis_offset.setObjectName("lineEdit_pelvis_offset")
        self.verticalLayout_2.addWidget(self.splitter_19)
        self.layoutWidget2 = QtWidgets.QWidget(self.widget)
        self.layoutWidget2.setGeometry(QtCore.QRect(770, 30, 321, 182))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.splitter_12 = QtWidgets.QSplitter(self.layoutWidget2)
        self.splitter_12.setMaximumSize(QtCore.QSize(314, 16777215))
        self.splitter_12.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_12.setObjectName("splitter_12")
        self.label_x_move_amplitude = QtWidgets.QLabel(self.splitter_12)
        self.label_x_move_amplitude.setMinimumSize(QtCore.QSize(250, 0))
        self.label_x_move_amplitude.setMaximumSize(QtCore.QSize(250, 16777215))
        self.label_x_move_amplitude.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_x_move_amplitude.setObjectName("label_x_move_amplitude")
        self.lineEdit_x_move_amplitude = QtWidgets.QLineEdit(self.splitter_12)
        self.lineEdit_x_move_amplitude.setMinimumSize(QtCore.QSize(60, 0))
        self.lineEdit_x_move_amplitude.setMaximumSize(QtCore.QSize(60, 16777215))
        self.lineEdit_x_move_amplitude.setObjectName("lineEdit_x_move_amplitude")
        self.verticalLayout_3.addWidget(self.splitter_12)
        self.splitter_13 = QtWidgets.QSplitter(self.layoutWidget2)
        self.splitter_13.setMaximumSize(QtCore.QSize(314, 16777215))
        self.splitter_13.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_13.setObjectName("splitter_13")
        self.label_y_move_amplitude = QtWidgets.QLabel(self.splitter_13)
        self.label_y_move_amplitude.setMinimumSize(QtCore.QSize(250, 0))
        self.label_y_move_amplitude.setMaximumSize(QtCore.QSize(250, 16777215))
        self.label_y_move_amplitude.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_y_move_amplitude.setObjectName("label_y_move_amplitude")
        self.lineEdit_y_move_amplitude = QtWidgets.QLineEdit(self.splitter_13)
        self.lineEdit_y_move_amplitude.setMinimumSize(QtCore.QSize(60, 0))
        self.lineEdit_y_move_amplitude.setMaximumSize(QtCore.QSize(60, 16777215))
        self.lineEdit_y_move_amplitude.setObjectName("lineEdit_y_move_amplitude")
        self.verticalLayout_3.addWidget(self.splitter_13)
        self.splitter_14 = QtWidgets.QSplitter(self.layoutWidget2)
        self.splitter_14.setMaximumSize(QtCore.QSize(314, 16777215))
        self.splitter_14.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_14.setObjectName("splitter_14")
        self.label_z_move_amplitude = QtWidgets.QLabel(self.splitter_14)
        self.label_z_move_amplitude.setMinimumSize(QtCore.QSize(250, 0))
        self.label_z_move_amplitude.setMaximumSize(QtCore.QSize(250, 16777215))
        self.label_z_move_amplitude.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_z_move_amplitude.setObjectName("label_z_move_amplitude")
        self.lineEdit_z_move_amplitude = QtWidgets.QLineEdit(self.splitter_14)
        self.lineEdit_z_move_amplitude.setMinimumSize(QtCore.QSize(60, 0))
        self.lineEdit_z_move_amplitude.setMaximumSize(QtCore.QSize(60, 16777215))
        self.lineEdit_z_move_amplitude.setObjectName("lineEdit_z_move_amplitude")
        self.verticalLayout_3.addWidget(self.splitter_14)
        self.splitter_15 = QtWidgets.QSplitter(self.layoutWidget2)
        self.splitter_15.setMaximumSize(QtCore.QSize(314, 16777215))
        self.splitter_15.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_15.setObjectName("splitter_15")
        self.label_angle_move_amplitude = QtWidgets.QLabel(self.splitter_15)
        self.label_angle_move_amplitude.setMinimumSize(QtCore.QSize(250, 0))
        self.label_angle_move_amplitude.setMaximumSize(QtCore.QSize(250, 16777215))
        self.label_angle_move_amplitude.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_angle_move_amplitude.setObjectName("label_angle_move_amplitude")
        self.lineEdit_angle_move_amplitude = QtWidgets.QLineEdit(self.splitter_15)
        self.lineEdit_angle_move_amplitude.setMinimumSize(QtCore.QSize(60, 0))
        self.lineEdit_angle_move_amplitude.setMaximumSize(QtCore.QSize(60, 16777215))
        self.lineEdit_angle_move_amplitude.setObjectName("lineEdit_angle_move_amplitude")
        self.verticalLayout_3.addWidget(self.splitter_15)
        self.splitter_16 = QtWidgets.QSplitter(self.layoutWidget2)
        self.splitter_16.setMaximumSize(QtCore.QSize(314, 16777215))
        self.splitter_16.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_16.setObjectName("splitter_16")
        self.label_arm_swing_gain = QtWidgets.QLabel(self.splitter_16)
        self.label_arm_swing_gain.setMinimumSize(QtCore.QSize(250, 0))
        self.label_arm_swing_gain.setMaximumSize(QtCore.QSize(250, 16777215))
        self.label_arm_swing_gain.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_arm_swing_gain.setObjectName("label_arm_swing_gain")
        self.lineEdit_arm_swing_gain = QtWidgets.QLineEdit(self.splitter_16)
        self.lineEdit_arm_swing_gain.setMinimumSize(QtCore.QSize(60, 0))
        self.lineEdit_arm_swing_gain.setMaximumSize(QtCore.QSize(60, 16777215))
        self.lineEdit_arm_swing_gain.setObjectName("lineEdit_arm_swing_gain")
        self.verticalLayout_3.addWidget(self.splitter_16)
        self.splitter_20 = QtWidgets.QSplitter(self.layoutWidget2)
        self.splitter_20.setMaximumSize(QtCore.QSize(314, 16777215))
        self.splitter_20.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_20.setObjectName("splitter_20")
        self.label_hip_pitch_offset = QtWidgets.QLabel(self.splitter_20)
        self.label_hip_pitch_offset.setMinimumSize(QtCore.QSize(250, 0))
        self.label_hip_pitch_offset.setMaximumSize(QtCore.QSize(250, 16777215))
        self.label_hip_pitch_offset.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_hip_pitch_offset.setObjectName("label_hip_pitch_offset")
        self.lineEdit_hip_pitch_offset = QtWidgets.QLineEdit(self.splitter_20)
        self.lineEdit_hip_pitch_offset.setMinimumSize(QtCore.QSize(60, 0))
        self.lineEdit_hip_pitch_offset.setMaximumSize(QtCore.QSize(60, 16777215))
        self.lineEdit_hip_pitch_offset.setObjectName("lineEdit_hip_pitch_offset")
        self.verticalLayout_3.addWidget(self.splitter_20)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "walking contrller 1.0"))
        self.pushButton_stop.setText(_translate("Form", "stop"))
        self.pushButton_apply.setText(_translate("Form", "apply"))
        self.pushButton_start.setText(_translate("Form", "start"))
        self.label_init_x_offset.setText(_translate("Form", "init_x_offset(初始姿态在X方向(前后)偏移)"))
        self.lineEdit_init_x_offset.setText(_translate("Form", "0.0"))
        self.label_2.setText(_translate("Form", "init_y_offset(初始姿态在Y方向(左右)偏移)"))
        self.lineEdit_init_y_offset.setText(_translate("Form", "0.0"))
        self.label_init_z_offset.setText(_translate("Form", "init_z_offset(初始姿态在Z方向(上下)偏移)"))
        self.lineEdit_init_z_offset.setText(_translate("Form", "0.025"))
        self.label_init_roll_offset.setText(_translate("Form", "init_roll_offset(初始姿态左右倾斜偏移)"))
        self.lineEdit_init_roll_offset.setText(_translate("Form", "0"))
        self.label_init_pitch_offset.setText(_translate("Form", "init_pitch_offset(初始姿态前后倾斜偏移)"))
        self.lineEdit_init_pitch_offset.setText(_translate("Form", "0"))
        self.label_init_yaw_offset.setText(_translate("Form", "init_yaw_offset(初始姿态旋转偏移)"))
        self.lineEdit_init_yaw_offset.setText(_translate("Form", "0"))
        self.label_period_time.setText(_translate("Form", "period_time(周期（左右脚各抬一次腿)）"))
        self.lineEdit_period_time.setText(_translate("Form", "800"))
        self.label_dsp_ratio.setText(_translate("Form", "dsp_ratio(一个周期里双脚着地时间占比)"))
        self.lineEdit_dsp_ratio.setText(_translate("Form", "0.2"))
        self.label_step_fb_ratio.setText(_translate("Form", "step_fb_ratio(左脚和右脚间X方向的距离)"))
        self.lineEdit_step_fb_ratio.setText(_translate("Form", "0.28"))
        self.label_y_swap_amplitude.setText(_translate("Form", "y_swap_amplitude(左右摆动的距离)"))
        self.lineEdit_y_swap_amplitude.setText(_translate("Form", "0.028"))
        self.label_z_swap_amplitude.setText(_translate("Form", "z_swap_amplitude(上下浮动的距离)"))
        self.lineEdit_z_swap_amplitude.setText(_translate("Form", "0.006"))
        self.label_pelvis_offset.setText(_translate("Form", "pelvis_offset(臀部关节左右摆动的距离)"))
        self.lineEdit_pelvis_offset.setText(_translate("Form", "0.5"))
        self.label_x_move_amplitude.setText(_translate("Form", "x_move_amplitude(向X方向移动距离)"))
        self.lineEdit_x_move_amplitude.setText(_translate("Form", "0.02"))
        self.label_y_move_amplitude.setText(_translate("Form", "y_move_amplitude(向Y方向移动距离)"))
        self.lineEdit_y_move_amplitude.setText(_translate("Form", "0.00"))
        self.label_z_move_amplitude.setText(_translate("Form", "z_move_amplitude(抬脚高度)"))
        self.lineEdit_z_move_amplitude.setText(_translate("Form", "0.02"))
        self.label_angle_move_amplitude.setText(_translate("Form", "angle_move_amplitude(转弯度)"))
        self.lineEdit_angle_move_amplitude.setText(_translate("Form", "0.0"))
        self.label_arm_swing_gain.setText(_translate("Form", "arm_swing_gain"))
        self.lineEdit_arm_swing_gain.setText(_translate("Form", "0"))
        self.label_hip_pitch_offset.setText(_translate("Form", "hip_pitch_offset(臀部前后倾斜角度)"))
        self.lineEdit_hip_pitch_offset.setText(_translate("Form", "7"))
