lab:
  Mono:
    black:
      max:
      - 123
      - 255
      - 255
      min:
      - 0
      - 0
      - 0
    blue:
      max:
      - 255
      - 174
      - 111
      min:
      - 0
      - 0
      - 0
    green:
      max:
      - 255
      - 110
      - 255
      min:
      - 47
      - 0
      - 135
    red:
      max:
      - 255
      - 255
      - 255
      min:
      - 0
      - 150
      - 130
    white:
      max:
      - 255
      - 255
      - 255
      min:
      - 193
      - 0
      - 0
    yellow:
      max:
      - 255
      - 255
      - 255
      min:
      - 153
      - 117
      - 146
  Stereo:
    black:
      max:
      - 123
      - 255
      - 255
      min:
      - 0
      - 0
      - 0
    blue:
      max:
      - 255
      - 143
      - 105
      min:
      - 0
      - 0
      - 0
    green:
      max:
      - 255
      - 110
      - 255
      min:
      - 47
      - 0
      - 135
    red:
      max:
      - 255
      - 255
      - 255
      min:
      - 0
      - 150
      - 144
    white:
      max:
      - 255
      - 255
      - 255
      min:
      - 193
      - 0
      - 0
    yellow:
      max:
      - 255
      - 255
      - 255
      min:
      - 117
      - 120
      - 130
size:
  height:
  - 480
  width:
  - 640
